import type { ContentStrategy } from '../config/config.js';
import type { ContentType, DifficultyLevel, StoredPost, TopicCandidate } from '../types.js';

/**
 * System prompt (SPEC section 15). Kept close to the specification's wording
 * so behavior stays predictable and auditable.
 */
export const SYSTEM_PROMPT = `You are a professional LinkedIn technical content writer.

Your task is to create one original LinkedIn post about cloud computing,
virtualization, DevOps, DevSecOps, Kubernetes, Docker, Linux,
networking, infrastructure as code, cloud security, or related topics.

The author is building a professional profile focused on cloud computing
and virtualization.

Write like a real technical professional who is learning, experimenting,
and developing practical knowledge.

The content must:
- be technically accurate
- be useful
- be understandable
- sound human
- avoid generic AI language
- avoid exaggerated claims
- avoid fake experience
- avoid fake certifications
- avoid fake projects
- avoid clickbait
- avoid excessive hashtags
- avoid repetitive introductions
- avoid repetitive conclusions

Do not claim that the author performed an action unless that action
is explicitly provided in the input context.

Do not invent personal experiences, employers, clients, certifications, or
specific production deployments. Prefer phrasing like "I'm learning...",
"I researched...", "I've been exploring..." over "I deployed..." or
"I built this for a client...".

The post should teach the reader something.

Return structured JSON only, matching the provided response schema exactly.`;

export interface PromptContext {
  strategy: ContentStrategy;
  topic: TopicCandidate;
  contentType: ContentType;
  difficulty: DifficultyLevel;
  recentPosts: StoredPost[];
  recentTopics: string[];
  formatHint: string;
}

/** Rotating structural formats so posts don't all look identical (SPEC section 18). */
export const WRITING_FORMATS: { name: string; structure: string }[] = [
  { name: 'Format A', structure: 'Observation -> Explanation -> Example -> Takeaway' },
  { name: 'Format B', structure: 'Question -> Explanation -> Example -> Conclusion' },
  { name: 'Format C', structure: 'Common misconception -> Reality -> Technical explanation' },
  { name: 'Format D', structure: 'Problem -> Solution -> Why it matters' },
  { name: 'Format E', structure: '"What I learned about X" -> Explanation -> Practical takeaway' },
];

export function pickWritingFormat(seedIndex: number): { name: string; structure: string } {
  const format = WRITING_FORMATS[seedIndex % WRITING_FORMATS.length];
  return format ?? WRITING_FORMATS[0]!;
}

const MAX_RECENT_POSTS_IN_PROMPT = 20;

export function buildUserPrompt(context: PromptContext): string {
  const { strategy, topic, contentType, difficulty, recentPosts, recentTopics, formatHint } = context;

  const limitedRecentPosts = recentPosts.slice(0, MAX_RECENT_POSTS_IN_PROMPT);
  const recentPostSummaries = limitedRecentPosts
    .map((p) => `- [${p.category}] "${p.topic}" (${p.contentType})`)
    .join('\n') || '(none yet - this is one of the first posts)';

  const recentTopicsList = recentTopics.slice(0, MAX_RECENT_POSTS_IN_PROMPT).join(', ') || '(none yet)';

  return `USER PROFILE
Name: ${strategy.profile.name}
Career goal: ${strategy.profile.careerGoal}
Experience level: ${strategy.profile.experienceLevel}
Location: ${strategy.profile.location}

CONTENT STRATEGY
Tone: ${strategy.style.tone}
Technical level: ${strategy.style.technicalLevel}
Avoid corporate language: ${strategy.style.avoidCorporateLanguage}
Avoid generic motivation: ${strategy.style.avoidGenericMotivation}
Avoid clickbait: ${strategy.style.avoidClickbait}
Use personal learning perspective: ${strategy.style.usePersonalLearningPerspective}

RECENT POSTS (last ${limitedRecentPosts.length}, avoid repeating these topics/structures)
${recentPostSummaries}

RECENT TOPICS (avoid these or very close variations)
${recentTopicsList}

FORBIDDEN/OVERUSED TOPICS
Do not write about any topic listed above in "RECENT TOPICS" using different wording.

CURRENT TOPIC
${topic.topic} (category: ${topic.category})
Relevant keywords: ${topic.keywords.join(', ')}

CONTENT TYPE
${contentType}

DIFFICULTY LEVEL
${difficulty}

WRITING RULES
- Structure this post using ${formatHint}. Do not use a generic "hook / 3 bullet points / conclusion" template every time.
- Length target: between ${strategy.quality.minLength} and ${strategy.quality.maxLength} characters total (hook + body combined).
- Use ${strategy.hashtags.minimum}-${strategy.hashtags.maximum} relevant hashtags. Prefer from this list when appropriate: ${strategy.hashtags.preferred.join(', ')}.
- Short paragraphs, blank lines between ideas, minimal emojis, no excessive Unicode decoration.
- Do not include a "Generated by AI" disclosure.
- Do not invent URLs or sources.
- Never write domain-like tokens such as your-app.com or example.com. LinkedIn auto-linkifies them. Say "the application hostname" instead.

Return ONLY the structured JSON object described by the response schema. Do not include markdown code fences or any extra commentary.`;
}

/** JSON schema the AI must conform to (SPEC section 16). Used for structured output. */
export const GENERATED_POST_SCHEMA = {
  type: 'object',
  properties: {
    topic: { type: 'string' },
    category: { type: 'string' },
    contentType: {
      type: 'string',
      enum: [
        'technical_explanation',
        'comparison',
        'common_mistake',
        'architecture',
        'troubleshooting',
        'learning_in_public',
        'project_insight',
        'concept_breakdown',
        'interview_concept',
        'question_discussion',
        'mini_case_study',
      ],
    },
    hook: { type: 'string' },
    body: { type: 'string' },
    hashtags: { type: 'array', items: { type: 'string' } },
    keywords: { type: 'array', items: { type: 'string' } },
  },
  required: ['topic', 'category', 'contentType', 'hook', 'body', 'hashtags', 'keywords'],
} as const;
